#The title appears on the first page
title: The Astronomy Club

#The description appears on the first page below the title
description: Welcome Stargazer!

#The logo appears as a small circular image above the title
logo: /assets/img/logo.png 

#The background of the front page
indexBG: /assets/img/bg/background.jpg

#The text color for the club name(i.e. the title). You can give the color in rgb too.
clubNameColor: white

#The font for the club name
clubNameFont: Arial, Helvetica, sans-serif

#The font for everything in the header
headerFont:

#The fontcolor of everything in the header
headerFontColor:

#The background of the header. If you want image, leave the headerBackgroundColor empty.
headerBackgroundImage:
headerBackgroundColor:

#The font for everything in the footer
footerFont: Arial, Helvetica, sans-serif

#The fontcolor of everything in the footer
footerFontColor: white

#The background color of the footer
footerBackgroundColor: black
footerBackgroundImage: /assets/img/bg/background.jpg

#The list of pages on your website
pageList:
  - name: Home
    url: /home.html/
  - name: Past Events
    url: /pastEvents.html/
  - name: People
    url: /people.html/

collections:
  events:
    output: true
  