#The title appears on the first page
title: The Astronomy Club

#The description appears on the first page below the title
description: Welcome Stargazer!

#The logo appears as a small circular image above the title
logo: /assets/img/logo.png 

#The background of the front page
indexBG: /assets/img/bg/background.jpg

#The text color for the club name(i.e. the title). You can give the color in rgb too.
clubNameColor: white

#The font for the club name
clubNameFont: Arial, Helvetica, sans-serif

#The font color for everything else on the first page
indexFontColor: white

#The font for everything else on the first page
indexFont: Arial, Helvetica, sans-serif
